# Generated by Django 5.0.1 on 2024-01-07 00:03

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del género')),
                ('genre_description', models.TextField(blank=True, null=True, verbose_name='Descripción del género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, unique=True, verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['language_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_title', models.CharField(max_length=250, unique=True, verbose_name='Titulo')),
                ('serie_synopsis', models.TextField(blank=True, null=True, verbose_name='sinopsis')),
                ('serie_date_of_issue', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de emisión')),
                ('serie_upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('serie_status', models.CharField(choices=[('Broadcast', 'En emision'), ('Concluded', 'Concluido')], default='Broadcast', max_length=20, verbose_name='Estado')),
                ('serie_image_file', models.FileField(upload_to=core.models.Series.get_upload_path_img, verbose_name='Imagen de portada')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('serie_genre', models.ManyToManyField(blank=True, to='core.genre', verbose_name='Géneros')),
                ('serie_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language', verbose_name='Idioma')),
                ('serie_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['serie_upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveBigIntegerField(verbose_name='Numero capitulo')),
                ('chapter_video', models.FileField(upload_to=core.models.get_upload_path_vid, verbose_name='Archivo de video')),
                ('chapter_upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('chapter_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.series', verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
                'ordering': ['chapter_upload_date'],
                'unique_together': {('chapter_title', 'chapter_number')},
            },
        ),
    ]
