# Generated by Django 5.0.1 on 2024-01-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_series_serie_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'ordering': ['-chapter_upload_date'], 'verbose_name': 'Capitulo', 'verbose_name_plural': 'Capitulos'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-serie_upload_date'], 'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
    ]
