# Generated by Django 5.0.1 on 2024-01-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chapters_options_alter_series_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='slug',
            new_name='chapter_slug',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='slug',
            new_name='serie_slug',
        ),
    ]
